[versions]
agp = "8.13.0"
kotlin = "2.2.20"
coreKtx = "1.17.0"
xposedApi = "82"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
xposedApi = { group = "de.robv.android.xposed", name = "api", version.ref = "xposedApi" }
